import { Exercise } from './types';

export const EXERCISES: Exercise[] = [
  {
    id: '01',
    title: 'Carré',
    difficulty: 'Facile',
    stars: 1,
    url: 'https://scratch.mit.edu/projects/857239112',
    thumbnailDescription: 'carré',
  },
  {
    id: '02',
    title: 'Triangle équilatéral',
    difficulty: 'Facile',
    stars: 1,
    url: 'https://scratch.mit.edu/projects/857241277',
    thumbnailDescription: 'triangle',
  },
  {
    id: '03',
    title: 'Pentagone régulier',
    difficulty: 'Moyen',
    stars: 2,
    url: 'https://scratch.mit.edu/projects/857219418',
    thumbnailDescription: 'pentagone',
  },
  {
    id: '04',
    title: 'Hexagone régulier',
    difficulty: 'Moyen',
    stars: 2,
    url: 'https://scratch.mit.edu/projects/857242797',
    thumbnailDescription: 'hexagone',
  },
  {
    id: '05',
    title: 'Octogone régulier',
    difficulty: 'Moyen',
    stars: 2,
    url: 'https://scratch.mit.edu/projects/857243326',
    thumbnailDescription: 'octogone',
  },
  {
    id: '06',
    title: 'Décagone régulier',
    difficulty: 'Moyen',
    stars: 2,
    url: 'https://scratch.mit.edu/projects/857243489',
    thumbnailDescription: 'décagone',
  },
  {
    id: '07',
    title: 'Escaliers',
    difficulty: 'Facile',
    stars: 1,
    url: 'https://scratch.mit.edu/projects/857245506',
    thumbnailDescription: 'escaliers',
  },
  {
    id: '08',
    title: 'Créneaux',
    difficulty: 'Facile',
    stars: 1,
    url: 'https://scratch.mit.edu/projects/857245615',
    thumbnailDescription: 'créneaux',
  },
  {
    id: '09',
    title: 'Triples créneaux',
    difficulty: 'Moyen',
    stars: 2,
    url: 'https://scratch.mit.edu/projects/857245833',
    thumbnailDescription: 'triples_créneaux',
  },
  {
    id: '10',
    title: 'Croix',
    difficulty: 'Facile',
    stars: 1,
    url: 'https://scratch.mit.edu/projects/857245961',
    thumbnailDescription: 'croix',
  },
  {
    id: '11',
    title: 'Spirale carrée 1',
    difficulty: 'Moyen',
    stars: 2,
    url: 'https://scratch.mit.edu/projects/857246093',
    thumbnailDescription: 'spirale_carrée_1',
  },
  {
    id: '12',
    title: 'Spirale carrée 2',
    difficulty: 'Moyen',
    stars: 2,
    url: 'https://scratch.mit.edu/projects/857246781',
    thumbnailDescription: 'spirale_carrée_2',
  },
  {
    id: '13',
    title: 'Spirale triangulaire',
    difficulty: 'Difficile',
    stars: 3,
    url: 'https://scratch.mit.edu/projects/1031904142',
    thumbnailDescription: 'spirale_triangulaire',
  },
  {
    id: '14',
    title: 'Spirale pentagonale',
    difficulty: 'Difficile',
    stars: 3,
    url: 'https://scratch.mit.edu/projects/1036693970',
    thumbnailDescription: 'spirale_pentagonale',
  },
  {
    id: '15',
    title: 'Triangles imbriqués',
    difficulty: 'Difficile',
    stars: 3,
    url: 'https://scratch.mit.edu/projects/1036694786',
    thumbnailDescription: 'triangles_imbriqués',
  },
  {
    id: '16',
    title: 'Hexagone et diagonales',
    difficulty: 'Difficile',
    stars: 3,
    url: 'https://scratch.mit.edu/projects/1184129817',
    thumbnailDescription: 'hexagone_diagonales',
  },
];
